[package]
name = "afterwork"
version = "2.0.0"
description = "A softer landing after work"
authors = ["sunnymoore1314-coder"]
edition = "2021"

[lib]
name = "afterwork_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

