"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, KeyRound, LoaderCircle, ShieldCheck, SlidersHorizontal, Trash2 } from "lucide-react";
import { Brand, Footer } from "@/components/Brand";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useLanguage } from "@/components/LanguageProvider";
import { clearProviderSettings, loadProviderSettings, providerDefaultModel, saveProviderSettings, testProvider, type PlannerProvider, type ProviderSettings } from "@/lib/provider";
import { clearPreferences, defaultPreferences, loadPreferences, savePreferences, type PersonalPreferences } from "@/lib/preferences";

export default function SettingsPage(){
 const {t}=useLanguage();
 const [settings,setSettings]=useState<ProviderSettings>({provider:"manual",apiKey:"",model:"",baseUrl:""});
 const [preferences,setPreferences]=useState<PersonalPreferences>(defaultPreferences);
 const [status,setStatus]=useState<""|"testing"|"ok"|"error">("");
 const [message,setMessage]=useState("");
 useEffect(()=>{setSettings(loadProviderSettings());setPreferences(loadPreferences())},[]);
 const update=(key:keyof ProviderSettings,value:string)=>setSettings(current=>({...current,[key]:value}));
 const updatePreference=(key:keyof PersonalPreferences,value:string)=>setPreferences(current=>({...current,[key]:value} as PersonalPreferences));
 function save(){saveProviderSettings(settings);setStatus("ok");setMessage(t("settingsSaved"))}
 function useManual(){clearProviderSettings();setSettings({provider:"manual",apiKey:"",model:"",baseUrl:""});setStatus("ok");setMessage(t("manualEnabled"))}
 function saveProfile(){savePreferences(preferences);setStatus("ok");setMessage(t("profileSaved"))}
 function resetProfile(){clearPreferences();setPreferences(defaultPreferences);setStatus("ok");setMessage(t("profileCleared"))}
 async function test(){setStatus("testing");setMessage("");const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),20000);try{await testProvider(settings,controller.signal);setStatus("ok");setMessage(t("connectionOk"))}catch(error){setStatus("error");setMessage(error instanceof Error?error.message:t("connectionFailed"))}finally{clearTimeout(timer)}}
 return <div className="site-shell"><Brand/><main className="settings-main"><Link href="/" className="back-link"><ArrowLeft size={16}/>{t("back")}</Link>
 <div className="settings-heading"><KeyRound size={30}/><p className="eyebrow">{t("aiSettingsEyebrow")}</p><h1>{t("aiSettings")}</h1><p>{t("aiSettingsIntro")}</p></div>
 <section className="settings-card"><label className="field-label" htmlFor="provider">{t("provider")}</label><select id="provider" value={settings.provider} onChange={e=>update("provider",e.target.value as PlannerProvider)}><option value="manual">{t("manualMode")}</option><option value="openrouter">{t("openRouter")}</option><option value="openai">OpenAI</option><option value="deepseek">DeepSeek</option><option value="custom">{t("customApi")}</option></select>{settings.provider!=="manual"&&<>{settings.provider==="openrouter"&&<p className="provider-note">{t("openRouterNote")} <a href="https://openrouter.ai/settings/keys" target="_blank" rel="noreferrer">{t("getOpenRouterKey")}</a></p>}<label className="field-label" htmlFor="api-key">API Key</label><Input id="api-key" type="password" autoComplete="off" value={settings.apiKey} onChange={e=>update("apiKey",e.target.value)} placeholder="sk-…"/><label className="field-label" htmlFor="model">{t("model")}</label><Input id="model" value={settings.model} onChange={e=>update("model",e.target.value)} placeholder={providerDefaultModel(settings.provider)||t("modelPlaceholder")}/>{settings.provider==="custom"&&<><label className="field-label" htmlFor="base-url">Base URL</label><Input id="base-url" inputMode="url" value={settings.baseUrl} onChange={e=>update("baseUrl",e.target.value)} placeholder="https://example.com/v1"/></>}<div className="privacy-box"><ShieldCheck size={19}/><span>{t("keyPrivacy")}</span></div><div className="settings-actions"><Button type="button" className="secondary-settings" onClick={test} disabled={status==="testing"}>{status==="testing"&&<LoaderCircle className="spin" size={17}/>} {t("testConnection")}</Button><Button type="button" onClick={save}>{t("saveSettings")}</Button></div></>}{settings.provider==="manual"&&<Button type="button" onClick={useManual}>{t("keepManual")}</Button>}</section>
 <div className="settings-heading profile-heading"><SlidersHorizontal size={27}/><p className="eyebrow">{t("personalDefaults")}</p><h2>{t("yourPreferences")}</h2><p>{t("preferencesIntro")}</p></div>
 <section className="settings-card profile-card"><div className="profile-grid"><div><label className="field-label" htmlFor="default-minutes">{t("defaultTime")}</label><select id="default-minutes" value={preferences.minutes} onChange={e=>updatePreference("minutes",e.target.value)}>{[15,30,45,60].map(n=><option value={n} key={n}>{n} {t("minutes")}</option>)}</select></div><div><label className="field-label" htmlFor="default-budget">{t("defaultBudget")}</label><select id="default-budget" value={preferences.budget} onChange={e=>updatePreference("budget",e.target.value)}><option value="0">{t("free")}</option><option value="30">&lt; ¥30</option><option value="100">&lt; ¥100</option></select></div><div><label className="field-label" htmlFor="default-place">{t("defaultPlace")}</label><select id="default-place" value={preferences.place} onChange={e=>updatePreference("place",e.target.value)}><option value="indoors">{t("indoors")}</option><option value="outside">{t("outside")}</option><option value="either">{t("either")}</option></select></div></div><label className="field-label" htmlFor="likes">{t("likedActivities")}</label><Textarea id="likes" value={preferences.likes} maxLength={300} onChange={e=>updatePreference("likes",e.target.value)} placeholder={t("likedPlaceholder")}/><label className="field-label" htmlFor="avoid">{t("avoidActivities")}</label><Textarea id="avoid" value={preferences.avoid} maxLength={300} onChange={e=>updatePreference("avoid",e.target.value)} placeholder={t("avoidPlaceholder")}/><div className="settings-actions"><Button type="button" className="secondary-settings" onClick={resetProfile}><Trash2 size={16}/>{t("clearPreferences")}</Button><Button type="button" onClick={saveProfile}>{t("savePreferences")}</Button></div></section>
 {message&&<p className={`settings-status ${status}`} role="status">{status==="ok"&&<CheckCircle2 size={16}/>} {message}</p>}</main><Footer/></div>}
